### ISSUE TITLE
Making upfirdn work in Python 3

### ISSUE THREAD

**Issue by GoogleCodeExporter** [sirtom67/upfirdn#4]
```
Hi, I spent a few minutes to make upfirdn work on Python 3.  I haven't tested 
extensively yet, but the test() function passes for python 2.7.6 and 3.4.0 on 
Ubuntu 14.04.

```

Original issue reported on code.google.com by `Joachim....@gmail.com` on 23 Jun 2015 at 11:17

Attachments:
- [upfirdn.hgdiff](https://storage.googleapis.com/google-code-attachments/upfirdn/issue-4/comment-0/upfirdn.hgdiff)

**Comment by GoogleCodeExporter** [comment]
```
Thanks for the contribution Joachim. I'll test it out in python 2 at least, if 
that checks out I'll go ahead and commit.
Regards,
  Tom
```

Original comment by `thomas.p...@gmail.com` on 23 Jun 2015 at 12:43

**Comment by sirtom67** [comment]
works in python3 for me. Closing this issue.
